name: Trigger auto deployment for cantieridemo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cantieridemo-AutoDeployTrigger-b7c11e7c-d6b5-46e2-b49a-87eb0b1a0195.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CANTIERIDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CANTIERIDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CANTIERIDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: custommcp.azurecr.io
          registryUsername: ${{ secrets.CANTIERIDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CANTIERIDEMO_REGISTRY_PASSWORD }}
          containerAppName: cantieridemo
          resourceGroup: CustomMCP
          imageToBuild: custommcp.azurecr.io/cantieridemo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


